### ISSUE TITLE
PS: Newbie here, I am unable to solve this error

### ISSUE THREAD

**Issue by eduanmoldeep** [jpatel0/ShareBy#1]
this error I am facing in just doing the first build after cloning it down...
Can you please help me out.
![image](https://user-images.githubusercontent.com/31613431/79076446-cde0c100-7d17-11ea-8a56-c38e685eb000.png)

**Comment by jpatel0** [comment]
Its a configuration for building the release version of the app.
You can remove that from the build.gradle file.
Or add those key-value pair in gradle.properties file for setting up the release version for the app

PS: Sorry for the late response
